version: '3.9'

services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 8080:8080
      - 443:443
    volumes:
      - ./config:/mosquitto/config
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log